[provider]
cluster = "localnet"
wallet = "~/Users/darius/solana-wallets/test-keypair.json"

[programs.localnet]
basic_1 = "HEmLMhV6WKBMrz3uMS9K9VcJ8JwVMroqSPqhZVFxUdsF"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
